### ISSUE TITLE
Passing combined reducer results in error / warning

### ISSUE THREAD

**Issue by benvp** [redux-offline/redux-offline#19]
Came around an issue, when passing a `rootReducer` which has been combined using `combineReducer` function from redux. Redux will raise a warning (or en error on react-native), stating that the key `offline`, which is added by the reducer enhancer function in `updater.js` is unexpected.

Well it's the intended behaviour of `combinedReducer` to warn if there is an unexpected key added. I'm just wondering how to get around this? I'm now using my own implementation of combineReducer to prevent the (in react-native very annoying) error.

![image](https://cloud.githubusercontent.com/assets/981344/24451502/60667498-147f-11e7-8aa8-b8c77dffd96c.png)

**Comment by jevakallio** [comment]
Ouch @benlime, that's no good. Thanks for submitting this issue. I will do my best to get to it tonight.

**Comment by TheoMer** [comment]
@jevakallio As per my post here: https://github.com/jevakallio/redux-offline/issues/27, I think the error was generated due to a service worker not being defined in my development environment.

Once I deployed to production, which has a service worker defined in index,html, I no longer receive the `Unexpected key "offline"` message.

See in devTools [here](https://learn-redux.firebaseapp.com)

**Comment by jevakallio** [comment]
> Once I deployed to production

Wait, you're already using this in production? 🥇 🌮  

@TheoMer but seriously, the reason you're not getting this in the prod build is that this error is a development-time warning, and the React/Redux prod build will strip these errors.

The underlying issue still exists and you will encounter it in dev. I fill fix and release this as soon as I am able to get to it

**Comment by TheoMer** [comment]
Sorry, I meant staging.  ;-)

**Comment by TheoMer** [comment]
Ok, on further investigation an 'redux-persist; cannot process cyclical state' error (See attached image) is generated when submitting a a comment. See in devTools [here](https://learn-redux.firebaseapp.com/)

Refer to my initial issue [#27](https://github.com/jevakallio/redux-offline/issues/27) for corresponding code review.

![error](https://cloud.githubusercontent.com/assets/15969262/24505848/652ce58c-1553-11e7-97fa-1f0f1b3977bc.jpg)

**Comment by jevakallio** [comment]
@benlime this has now been fixed and released as [v1.0.3](https://github.com/jevakallio/redux-offline/releases/tag/v1.0.3). Apologies for the delay getting this fixed, and thanks for reporting!

**Comment by jevakallio** [comment]
@TheoMer the issue "cannot process cyclical state" is unrelated, and is likely caused by your action payload being somehow cyclical (non-vanilla javascript objects). I took a look at the code you posted in #27, the possible culprits are the posts/comments.  

Because redux-persist needs to be able to serialize your state to JSON, you'll need to give it serializable objects.
